/* eslint-disable padding-line-between-statements */
export const BASE_URL = 'https://stockapi.nextlevelgroup.uz/api/v1/'

export const AUTH_URL = 'auth/'
export const USERS_URL = 'users/'
export const BRANDS_URL = 'brands/'
export const CATEGORIES_URL = 'categories/'
export const MEASUREMENTS_URL = 'unit-measures/'
export const PRODUCTS_URL = 'products/'
export const WAREHOUSES_URL = 'warehouses/'
export const SUPPLIERS_URL = 'suppliers/'
export const ENTRIES_URL = 'warehouse-incomes/'
export const WAREHOUSE_ITEMS_URL = 'warehouse-items/'
export const CURRENCIES_URL = 'currency-ratios/'
export const CLIENTS_CATEGORIES_URL = 'clients-categories/'
export const REGIONS_URL = 'regions/'
export const CITIES_URL = 'cities/'
export const CLIENTS_URL = 'clients/'
export const ORDERS_URL = 'orders/'
export const PAYMENTS_URL = 'payments/'
